[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm[toml]>=6.2",
     "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "hyperfast/_version.py"
local_scheme = "no-local-version"